### ISSUE TITLE
Getting error

### ISSUE THREAD

**Issue by gustavoriveray** [Ankitagupta2309/pushKnot#1]
Im installing by doing

`npm install https://github.com/Ankitagupta2309/pushKnot`

Then I get this warnings

```
npm WARN ENOENT ENOENT: no such file or directory, open '/Users/user/package.json'
npm WARN EPACKAGEJSON user No description
npm WARN EPACKAGEJSON user No repository field.
npm WARN EPACKAGEJSON user No README data
npm WARN EPACKAGEJSON user No license field.
```

then when trying to run

`node start.js --localhost`

I get

`````` module.js:328
    throw err;
    ^

Error: Cannot find module '/Users/user/folder/start.js'
    at Function.Module._resolveFilename (module.js:326:15)
    at Function.Module._load (module.js:277:25)
    at Function.Module.runMain (module.js:430:10)
    at startup (node.js:141:18)
    at node.js:1003:3```
``````

**Comment by Ankitagupta2309** [comment]
Hi Gustavo,
You need to first clone the repo by running 
git clone https://github.com/Ankitagupta2309/pushKnot.git
Then you would be able to run npm install.
For starting the proxy please use the below command
node start.js --domain=localhost.
